// Re-export all validation schemas from the new package for backward compatibility
export {
  uuidSchema,
  phoneSchema,
  emailSchema,
  dateSchema,
  paginationSchema,
  type PaginationInput,
  memberStage1Schema,
  memberStage2Schema,
  memberResponseSchema,
  type MemberStage1Input,
  type MemberStage2Input,
  type MemberResponse,
  childRegistrationSchema,
  childResponseSchema,
  parentSchema,
  parentResponseSchema,
  childParentLinkSchema,
  type ChildRegistrationInput,
  type ChildResponse,
  type ParentInput,
  type ParentResponse,
  type ChildParentLinkInput,
  annualPlanSchema,
  planGoalSchema,
  planActivitySchema,
  planDistributionSchema,
  weeklyPlanSchema,
  progressRecordSchema,
  type AnnualPlanInput,
  type PlanGoalInput,
  type PlanActivityInput,
  type PlanDistributionInput,
  type WeeklyPlanInput,
  type ProgressRecordInput,
  sessionSchema,
  attendanceUpdateSchema,
  batchVerifySchema,
  eventSchema,
  eventAssignmentSchema,
  type SessionInput,
  type AttendanceUpdateInput,
  type BatchVerifyInput,
  type EventInput,
  type EventAssignmentInput,
  assessmentSchema,
  scoreSchema,
  announcementSchema,
  reportGenerationSchema,
  type AssessmentInput,
  type ScoreInput,
  type AnnouncementInput,
  type ReportGenerationInput,
  apiResponseSchema,
  paginatedResponseSchema,
  type ApiResponseInput,
  type PaginatedResponseInput,
} from "@repo/validation";
