export {
  type AdminNavItem,
  type AdminNavRole,
  type AdminNavSection,
  type NavItem,
  type NavSection,
  type UserRole,
  adminNavigationConfig,
  findActiveNavItem,
  findAdminActiveNavItem,
  getAdminNavigationForRoles,
  getAdminPrimaryNavItems,
  getNavigationForRoles,
  getPrimaryNavItems,
  mapSessionRolesToAdminNavRoles,
  mapSessionRolesToNavRoles,
  navigationConfig,
} from "@/config/navigation";
